### ISSUE TITLE
rclcpp multithreading crashiness

### ISSUE THREAD

**Issue by rotu** [ros-tooling/aws-oncall#107] opened 2020-04-03 20:03 UTC
## Overview

Not sure where to escalate this, but I believe it's critical.

rclcpp is non-threadsafe in some very bad ways. For instance the constructors and destructors of Node can segfault if called in parallel.
This caused some test failures in https://github.com/ros2/rosbag2/issues/329 which have been narrowly fixed but the underlying issue persists. https://github.com/ros2/rclcpp/issues/1042 Because of the nature of this issue, I expect this to impact the stability of complex applications in widespread and hard-to-reproduce ways.

## Completion Criteria

- Investigate where any non-threadsafe `rcl_.*` interface functions may be called by `rclcpp` functions, which don't carry the same warning about lack of threadsafety.
- For such cases, where practical, enforce threadsafety in the rcl layer or the rclcpp layer (e.g. with mutex locking)
- If impractical, add instrumentation to make these unsafe obvious (e.g. with a semaphor and logging to know when a contended resource is being used unsafely

**Comment by thomas-moulard** [comment] 2020-04-03 20:06
Thanks for the bug report @rotu. I think this would be more visible in the `rclcpp` repo. Did you open a ticket there too?

**Comment by thomas-moulard** [comment] 2020-06-13 06:13
Closing as the issue is tracked in `rclcpp`.

**Closed by thomas-moulard** 2020-06-13 06:13 UTC
