### ISSUE TITLE
ros2action tests failing in ROS2 x86_64 Ubuntu Bionic Builds

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-oncall#9] opened 2019-11-26 00:39 UTC
## Overview

A `ros2action` test is failing in the nightly Ubuntu x86 builds.

Failing in `rmw_connext`

## Required Information

* **Job Home**: 
  * https://ci.ros2.org/view/nightly/job/nightly_linux_debug/
  * https://ci.ros2.org/view/nightly/job/nightly_linux_release/
* **First Failing Build** (or oldest/old-ish one with this issue that you can find, best effort): 
  * https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1451/
  * https://ci.ros2.org/view/nightly/job/nightly_linux_release/1436/
* **Latest Failing Build** (try to keep this up to date): 
* **External tracking ticket**: https://github.com/ros2/ros2cli/issues/450

**Comment by dabonnie** [comment] 2019-11-27 00:28
Opened PR: https://github.com/ros2/rclcpp/pull/930 for a simple lint test failure.

**Comment by dabonnie** [comment] 2019-11-27 22:03
PR merged into master.

**Comment by dabonnie** [comment] 2019-11-27 22:03
Leaving this open as there are other test failures.

**Comment by prajakta-gokhale** [comment] 2019-12-02 18:35
All builds have test failures:

* [Debug](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1394/#showFailuresLink)
* [Release](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1381/#showFailuresLink)
* [Packaging](https://ci.ros2.org/view/packaging/job/packaging_linux/1689/#showFailuresLink)

**Comment by zmichaels11** [comment] 2019-12-09 23:59
Probably caused by https://github.com/ros-security/aws-oncall/issues/26

**Comment by piraka9011** [comment] 2020-01-21 16:30
These tests still fail:

* projectroot.test_tutorial_parameter_events__rmw_connext_cpp
* rqt_reconfigure.test.test_flake8.test_flake8

This one seems like a simple fix [here](https://github.com/ros-visualization/rqt_reconfigure/blob/dashing/src/rqt_reconfigure/param_api.py)
```
./src/rqt_reconfigure/param_api.py:130:13: C407 Unnecessary list comprehension - 'filter' can take a generator.
            filter(lambda node_name: _has_params(node, node_name),
```

* demo_nodes_cpp.TestExecutablesTutorial.test_processes_output
* projectroot.test_parameter_server_cpp__rmw_fastrtps_cpp
* test_rclcpp.test_parameter_server_cpp__rmw_fastrtps_cpp.xunit.missing_result

**Comment by zmichaels11** [comment] 2020-01-27 15:55
Unstable: Debug, Release, Packaging

**Comment by emersonknapp** [comment] 2020-02-06 22:06
Now it is a failing test in ros2action

Opened issue https://github.com/ros2/ros2cli/issues/450

**Comment by prajakta-gokhale** [comment] 2020-02-21 20:01
Fix tracking issue https://github.com/ros2/ros2cli/issues/450 was discussed in the weekly OSRF meeting on 02/20 and assigned to an owner.

**Comment by piraka9011** [comment] 2020-05-22 17:00
Test is no longer failing.

**Closed by piraka9011** 2020-05-22 17:00 UTC
Labels: arch - x86_64, platform - Ubuntu, test failure
